version: "3"

networks:
  default:
    external:
      name: bridge

services:
  nginx:
    env_file: .env
    image: nginx:stable
    network_mode: bridge
    restart: always
    container_name: nginx
    ports:
      - ${PORT}:80
    volumes:
      - ./app:/var/www/bothelp
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/data/logs:/var/log/nginx/
    depends_on:
      - php
    links:
      - php
  php:
    env_file: .env
    network_mode: bridge
    restart: always
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./app:/var/www/bothelp
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
  rabbitmq:
    network_mode: bridge
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    #restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=rootpass
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./docker/rabbitmq/init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/init/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"